# Q1

In [17]:
import numpy as np
a = np.arange(1,13).reshape(3,4)
print("数组维度(ndim):",a.ndim)
print("形状(shape):",a.shape)
print("元素总个数(size):",a.size)
print("数组内容:\n",a)

数组维度(ndim): 2
形状(shape): (3, 4)
元素总个数(size): 12
数组内容:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Q2

In [18]:
import numpy as np
b_float = np.array([1.5,2.6,3.7,4.8])
print("转换前数组:",b_float)
print("转换前数据类型:",b_float.dtype.name)
b_int = b_float.astype(np.int32)
print("转换后数组:",b_int)
print("转换后数据类型:",b_int.dtype.name)

转换前数组: [1.5 2.6 3.7 4.8]
转换前数据类型: float64
转换后数组: [1 2 3 4]
转换后数据类型: int32


# Q3

In [19]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("原数组:\n",arr)
arr_1 = arr[0:2,1:3]
print("切片结果:\n",arr_1)

原数组:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
切片结果:
 [[2 3]
 [6 7]]


# Q4

In [20]:
import numpy as np
arr = np.array([10,15,20,25,30,35])
# 1.
a = arr[[1,3,5]]
print("第1、3、5个元素:",a)
# 2.
b = arr[arr > 20]
print("大于20的元素:", b)

第1、3、5个元素: [15 25 35]
大于20的元素: [25 30 35]


In [33]:
c = arr[(arr > 20) & (arr < 30)]
c

array([25])

# Q5

In [21]:
import numpy as np
zeros_arr = np.zeros((3,4))
arr_b = np.array([1,2,3,4])
c = zeros_arr + arr_b
print("广播相加结果:\n",c)

广播相加结果:
 [[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


# Q6

In [22]:
x = np.array([1,4,9,16])
y = np.array([2,1,4,5])
sqrt_x = np.sqrt(x)
print("x的平方根:", sqrt_x)
a = np.maximum(sqrt_x, y)
print("对应位置最大值:", a)

x的平方根: [1. 2. 3. 4.]
对应位置最大值: [2. 2. 4. 5.]


# Q7

In [23]:
a = np.arange(24).reshape(2,3,4)
a_trans = a.transpose((1,0,2))
print("转换后数组形状:", a_trans.shape)

转换后数组形状: (3, 2, 4)


# Q8

In [24]:
arr_x = np.array([1,5,7])
arr_y = np.array([2,6,8])
arr_con = np.array([True,False,True])
a8 = np.where(arr_con,arr_x,arr_y)
print("条件选择结果:", a8)

条件选择结果: [1 6 7]


# Q9

In [25]:
arr9 = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])
mean_val = arr9.mean()
print("所有元素平均值:", mean_val)

arr9.sort(axis=0)
print("按列排序后数组:\n", arr9)

所有元素平均值: 3.888888888888889
按列排序后数组:
 [[3 2 2]
 [4 3 2]
 [6 6 7]]


# Q10

In [28]:
np.random.seed(10)

A = np.random.rand(2, 2)
B = np.random.rand(2, 2)
print("矩阵A:\n", A)
print("矩阵B:\n", B)

dot_res = np.dot(A, B)
print("A和B的点积:\n", dot_res)

矩阵A:
 [[0.77132064 0.02075195]
 [0.63364823 0.74880388]]
矩阵B:
 [[0.49850701 0.22479665]
 [0.19806286 0.76053071]]
A和B的点积:
 [[0.38861894 0.18917279]
 [0.46418833 0.71193035]]
